### ISSUE TITLE
Unnamed dependency `bundler`

### ISSUE THREAD

**Issue by onlyhavecans** [stupied4ever/ruby-tapas-downloader#38]
When I first downloaded this into a fresh ruby it crashed on all runs because bundler was now found.
Bundler is a dependency of this gem but when I `gem install` it it does not install bundler.

**Comment by stupied4ever** [comment]
Sory for your bad experience, but I searched on some projects (dotenv, rspec) and any one depends on bundle (and both use it). Do you have some example of project that add bundle as a dependency?

**Comment by tbunnyman** [comment]
I searched github quickly and found more than a few projects that use 'gem bundler' in their Gemfiles. I can't tell you why rubocop would work but this program crashes with a failed dependency until installed on default OS X ruby
